#!/usr/bin/env python

# reads from a file holding structured data in json format
# and prints part of data

# NB this will fail if input file does not exist
#    qill also fail  if input file contains more than one record
#    (generated by running previous script more than once)

import json

f = open("example4.txt", "r+")
x = json.load(f)
print(x["firstName"])  # assumes only one record and it converts to dictionary
